name: deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Fetch latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16.15.0
      uses: actions/setup-node@v2
      with:
        node-version: '16.15.0'

    - name: Build Project
      run: |
        npm install
        npm run build

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        local-dir: './build/'
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME  }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: ${{ secrets.FTP_PORT }}
